# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Computational Neuroscience 
author: Elias Najarro & Rune Berg
logo: _static/media/cajal1.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: -1

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/BergLab/CompNeuroBook  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon                   : "favicon.png"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  # extra_footer              : <a href="https://neuroAIwithpython.com/">neurowithpython.com</a> <div id="wh-modal"> <button class="wh-venti-button" aria-label="close modal" id="wh-modal-close">✕</button> <img id="wh-modal-img"> </div>  # Will be displayed underneath the footer.
  # baseurl                   : "https://neuroAIwithpython.com"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  use_repository_button     : true
  use_issues_button         : true  # Whether to add an "open an issue" button
  use_edit_page_button      : true
  default_mode : light # https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/light-dark.html
  use_multitoc_numbering : false

html_theme_options:
  navbar_end : ["navbar-icon-links"]

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: ""

only_build_toc_files: true

exclude_patterns : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

nbsphinx_timeout : -1

# https://myst-parser.readthedocs.io/en/latest/syntax/optional.html

# parse:
#   myst_enable_extensions:
#     # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
#     # https://github.com/executablebooks/jupyter-book/blob/master/docs/_config.yml
#     - html_image